export const newsItems = [
  {
    id: 5,
    title: "分子ビューアを公開しました",
    date: "2025-11-13",
    category: "解説・学習",
    body: "代表的な分子構造をシンプルに切り替えて確認できるビューアを追加しました。",
    link: "/news-articles/article4.html",
    important: true,
  },
  {
    id: 4,
    title: "2D/3D グラフツールを公開しました",
    date: "2025-11-10",
    category: "お知らせ",
    body: "1つの画面で 2D と 3D を切り替えられる統合グラフツールを公開しました。学習やレポート作成に活用してください。",
    link: "/news-articles/article3.html",
    important: false,
  },
  {
    id: 3,
    title: "力学2 レポート1の解説動画を公開",
    date: "2025-10-12",
    category: "解説・学習",
    body: "大問ごとの解説動画と参考図へのリンクを掲載しました。レポート準備に役立ててください。",
    link: "/subjects/力学/videos-pages/video4.html",
    important: true,
  },
  {
    id: 2,
    title: "匿名掲示板をリリースしました",
    date: "2025-10-05",
    category: "お知らせ",
    body: "授業の疑問やTipsを共有できる匿名掲示板を追加しました。",
    link: "/news-articles/article2.html",
    important: false,
  },
  {
    id: 1,
    title: "WEBページを公開しました",
    date: "2025-09-18",
    category: "お知らせ",
    body: "学習サイトのWEBページを公開しました。ツール・科目一覧・掲示板を統合しています。",
    link: "/news-articles/article1.html",
    important: false,
  },
];
