export const newsItems = [
  {
    id: 1,
    title: "メンテナンス完了",
    date: "2025-11-01",
    category: "更新",
    body: "システム基盤をアップデートしました。より高速になりました。",
    important: true,
  },
  {
    id: 2,
    title: "匿名掲示板をリリース",
    date: "2025-10-28",
    category: "更新",
    body: "掲示板機能を追加しました。思ったことを気軽に共有できます。",
    important: false,
  },
  {
    id: 3,
    title: "計画メンテナンスのお知らせ",
    date: "2025-10-20",
    category: "メンテナンス",
    body: "11/15 深夜に1時間の停止が発生します。ご協力をお願いします。",
    important: true,
  },
  {
    id: 4,
    title: "科目一覧にCPを追加",
    date: "2025-10-05",
    category: "更新",
    body: "新たにCPの教材ダイジェストを公開しました。",
    important: false,
  },
  {
    id: 5,
    title: "利用上のお願い",
    date: "2025-09-30",
    category: "注意事項",
    body: "課題提出期限を守り、投稿は丁寧にお願いします。",
    important: false,
  },
  {
    id: 6,
    title: "学習サイクルに関するヒントを追加",
    date: "2025-09-18",
    category: "更新",
    body: "インデックスやツールページに新しいチップを追加しました。",
    important: false,
  },
];
